import type { Unit } from "./types";

// Română · capitolul 1 — cum arată proba, curentele literare și harta operelor
// canonice (autor · an · specie). Baza pentru Subiectul II și eseul de la Subiectul III.

export const curente: Unit = {
  id: "curente",
  subject: "romana",
  title: "Proba, curentele și operele",
  blurb: "Cum se punctează proba, ce curent e fiecare autor și harta operelor de studiat.",
  examRef: "Subiectele II și III",
  lessons: [
    {
      id: "proba-romana",
      title: "Cum arată proba",
      cards: [
        {
          type: "learn",
          title: "Trei subiecte, trei ore",
          body: "Proba scrisă la română durează **3 ore** și se notează cu 100 de puncte, din care 10 se dau din oficiu.\n\n**Subiectul I (50 p)**: A, cinci cerințe pe un text la prima vedere (30 p); B, un text argumentativ de minimum 150 de cuvinte (20 p).\n\n**Subiectul II (10 p)**: un text de minimum 50 de cuvinte despre un fragment literar.\n\n**Subiectul III (30 p)**: eseul, de minimum 400 de cuvinte, despre o operă studiată.",
        },
        {
          type: "calc",
          prompt: "Câte puncte se acordă din oficiu la proba de română?",
          answer: 10,
          unit: "puncte",
          explain: "Din 100 de puncte, 10 sunt din oficiu. Restul de 90 le iei pe cele trei subiecte.",
        },
        {
          type: "choice",
          prompt: "Care este numărul minim de cuvinte pentru eseul de la Subiectul III?",
          options: ["400", "150", "50", "250"],
          answer: 0,
          explain: "Eseul are minimum 400 de cuvinte. 150 e pragul textului argumentativ, iar 50 cel de la Subiectul II.",
        },
        {
          type: "truefalse",
          prompt: "Textul argumentativ de la Subiectul I, partea B, trebuie să aibă minimum 150 de cuvinte.",
          answer: true,
          explain: "Da. Sub prag pierzi puncte la încadrarea în limita de spațiu.",
        },
        {
          type: "learn",
          title: "Ce verifică fiecare subiect",
          body: "**Subiectul I** verifică dacă înțelegi un text nou: sensul unor cuvinte, idei, atitudini. Apoi ți se cere o opinie argumentată.\n\n**Subiectul II** verifică dacă știi să citești un text literar: rolul unui personaj, al unor figuri de stil, al notațiilor autorului.\n\n**Subiectul III** verifică dacă stăpânești operele canonice: temă, viziune, context, construcție.",
        },
        {
          type: "choice",
          prompt: "Câte puncte valorează eseul de la Subiectul III?",
          options: ["30", "50", "10", "20"],
          answer: 0,
          explain: "Subiectul III valorează 30 de puncte. Subiectul I e cel mai mare (50), iar Subiectul II are 10.",
        },
        {
          type: "calc",
          prompt: "Câte puncte valorează în total Subiectul I (A și B)?",
          answer: 50,
          unit: "puncte",
          explain: "A valorează 30 de puncte, B valorează 20: în total 50.",
        },
        {
          type: "truefalse",
          prompt: "La Subiectul II scrii un eseu de minimum 400 de cuvinte.",
          answer: false,
          explain: "La Subiectul II scrii un text scurt, de minimum 50 de cuvinte. Eseul lung vine la Subiectul III.",
        },
      ],
    },
    {
      id: "curente-literare",
      title: "Curentele literare",
      cards: [
        {
          type: "learn",
          title: "Romantismul",
          body: "Pune pe primul loc sentimentul, visul, natura și trecutul istoric. Personajele sunt excepționale, în situații excepționale.\n\nLa noi începe cu revista **Dacia literară** (1840), condusă de Mihail Kogălniceanu. În primul ei număr apare nuvela „Alexandru Lăpușneanul” de Costache Negruzzi.\n\n**Mihai Eminescu** e considerat ultimul mare romantic european.",
        },
        {
          type: "choice",
          prompt: "Ce revistă a deschis romantismul pașoptist românesc, în 1840?",
          options: ["Dacia literară", "Convorbiri literare", "Sburătorul", "Gândirea"],
          answer: 0,
          explain: "Dacia literară, condusă de Mihail Kogălniceanu, a apărut în 1840.",
        },
        {
          type: "learn",
          title: "Realismul",
          body: "Vrea să arate lumea așa cum este: medii sociale reale, personaje tipice, un narator obiectiv, la persoana a III-a.\n\nOpere de studiat: „Moara cu noroc” (Ioan Slavici), „Ion” (Liviu Rebreanu), „Enigma Otiliei” (George Călinescu), „Moromeții” (Marin Preda).",
        },
        {
          type: "learn",
          title: "Simbolismul",
          body: "Nu spune direct, ci **sugerează**: prin simboluri, culori, muzicalitate, corespondențe între simțuri. Stări apăsătoare: nevroza, spleen-ul, singurătatea.\n\nLa bac, reprezentantul e **George Bacovia**, cu poezia „Plumb”.",
        },
        {
          type: "choice",
          prompt: "Cărui curent literar îi aparține poezia „Plumb” de George Bacovia?",
          options: ["simbolismului", "romantismului", "realismului", "neomodernismului"],
          answer: 0,
          explain: "„Plumb” e poezia-emblemă a simbolismului românesc: sugestie, culoare, stare de apăsare.",
        },
        {
          type: "learn",
          title: "Modernism și tradiționalism",
          body: "Între cele două războaie mondiale, literatura se împarte în două direcții.\n\n**Modernismul**, susținut de Eugen Lovinescu prin cenaclul și revista **Sburătorul**, vrea sincronizarea cu literatura europeană: Tudor Arghezi, Lucian Blaga, Ion Barbu, Camil Petrescu.\n\n**Tradiționalismul**, în jurul revistei **Gândirea**, caută valorile satului, ale credinței și ale trecutului: Ion Pillat, Vasile Voiculescu.",
        },
        {
          type: "choice",
          prompt: "În jurul cărei reviste s-a grupat modernismul interbelic?",
          options: ["Sburătorul", "Gândirea", "Dacia literară", "Convorbiri literare"],
          answer: 0,
          explain: "Sburătorul, condus de Eugen Lovinescu. Gândirea era revista tradiționaliștilor.",
        },
        {
          type: "learn",
          title: "Neomodernismul",
          body: "După anii '60, o nouă generație redescoperă libertatea poeziei moderne, după anii de realism socialist impus.\n\nLa bac: **Nichita Stănescu** („Leoaică tânără, iubirea”) și **Marin Sorescu** (piesa „Iona”).",
        },
        {
          type: "truefalse",
          prompt: "Piesa „Iona” de Marin Sorescu aparține neomodernismului.",
          answer: true,
          explain: "Sorescu face parte din generația '60, a neomoderniștilor.",
        },
        {
          type: "truefalse",
          prompt: "Lucian Blaga este un poet tradiționalist, din grupul revistei Sburătorul.",
          answer: false,
          explain: "Blaga e un poet modernist. Iar Sburătorul era revista modernismului, nu a tradiționalismului.",
        },
      ],
    },
    {
      id: "opere-canonice",
      title: "Harta operelor",
      cards: [
        {
          type: "learn",
          title: "Proza: basm, nuvelă, roman",
          body: "**Basm cult**: „Povestea lui Harap-Alb”, Ion Creangă (1877).\n\n**Nuvele**: „Alexandru Lăpușneanul”, Costache Negruzzi (1840), nuvelă istorică romantică; „Moara cu noroc”, Ioan Slavici (1881), nuvelă psihologică realistă.\n\n**Romane**: „Ion”, Liviu Rebreanu (1920); „Baltagul”, Mihail Sadoveanu (1930); „Ultima noapte de dragoste, întâia noapte de război”, Camil Petrescu (1930); „Enigma Otiliei”, George Călinescu (1938); „Moromeții”, Marin Preda (volumul I, 1955).",
        },
        {
          type: "choice",
          prompt: "Cine a scris romanul „Ion”?",
          options: ["Liviu Rebreanu", "Marin Preda", "Camil Petrescu", "Mihail Sadoveanu"],
          answer: 0,
          explain: "„Ion” (1920) e romanul lui Liviu Rebreanu, un roman realist obiectiv.",
        },
        {
          type: "truefalse",
          prompt: "„Povestea lui Harap-Alb” este un basm popular.",
          answer: false,
          explain: "E un **basm cult**: are autor cunoscut, Ion Creangă. Basmul popular e anonim și circulă oral.",
        },
        {
          type: "learn",
          title: "Cine povestește?",
          body: "Diferența dintre roman **obiectiv** și roman **subiectiv** apare aproape sigur în eseu.\n\n„Ion” și „Enigma Otiliei” au un narator omniscient, la persoana a III-a, care știe tot și nu judecă.\n\n„Ultima noapte de dragoste, întâia noapte de război” are un **narator-personaj**, Ștefan Gheorghidiu, care povestește la persoana I ce simte și ce crede el.",
        },
        {
          type: "choice",
          prompt: "Cine povestește în „Ultima noapte de dragoste, întâia noapte de război”?",
          options: [
            "Ștefan Gheorghidiu, narator-personaj, la persoana I",
            "un narator omniscient, la persoana a III-a",
            "Ela, soția lui Gheorghidiu",
            "mai mulți naratori, pe rând",
          ],
          answer: 0,
          explain: "Romanul lui Camil Petrescu e subiectiv: totul e filtrat prin conștiința lui Ștefan Gheorghidiu.",
        },
        {
          type: "learn",
          title: "Dramaturgia",
          body: "**„O scrisoare pierdută”**, I. L. Caragiale (1884): comedie despre alegeri, șantaj și politică de provincie. Personaje: Ștefan Tipătescu, Zoe, Zaharia Trahanache, Nae Cațavencu, Agamiță Dandanache.\n\n**„Iona”**, Marin Sorescu (1968): „tragedie în patru tablouri”, o parabolă despre omul singur care își caută libertatea.",
        },
        {
          type: "choice",
          prompt: "Ce specie literară este „O scrisoare pierdută”?",
          options: ["comedie", "tragedie", "dramă", "basm cult"],
          answer: 0,
          explain: "Caragiale a scris-o ca o comedie: râsul vine din moravuri, limbaj și situații.",
        },
        {
          type: "choice",
          prompt: "Cine este personajul principal din „Moara cu noroc”?",
          options: ["Ghiță", "Ion", "Felix Sima", "Ilie Moromete"],
          answer: 0,
          explain: "Ghiță, cârciumarul care se lasă prins în jocul lui Lică Sămădăul.",
        },
        {
          type: "calc",
          prompt: "În ce an a apărut romanul „Ion” de Liviu Rebreanu?",
          answer: 1920,
          explain: "1920. E primul mare roman realist obiectiv al literaturii române.",
        },
      ],
    },
  ],
  test: [
    // proba
    {
      lesson: "proba-romana",
      type: "choice",
      prompt: "Cât durează proba scrisă la limba și literatura română?",
      options: ["3 ore", "2 ore", "4 ore", "90 de minute"],
      answer: 0,
      explain: "Proba durează 3 ore.",
    },
    {
      lesson: "proba-romana",
      type: "calc",
      prompt: "Câte puncte valorează Subiectul II?",
      answer: 10,
      unit: "puncte",
      explain: "Subiectul II valorează 10 puncte.",
    },
    {
      lesson: "proba-romana",
      type: "choice",
      prompt: "Care este numărul minim de cuvinte pentru textul de la Subiectul II?",
      options: ["50", "150", "400", "100"],
      answer: 0,
      explain: "Minimum 50 de cuvinte.",
    },
    {
      lesson: "proba-romana",
      type: "truefalse",
      prompt: "Subiectul I are cel mai mare punctaj dintre cele trei subiecte.",
      answer: true,
      explain: "Subiectul I are 50 de puncte, față de 10 (II) și 30 (III).",
    },
    // curente
    {
      lesson: "curente-literare",
      type: "choice",
      prompt: "Cărui curent îi aparține Mihai Eminescu?",
      options: ["romantismului", "simbolismului", "modernismului", "neomodernismului"],
      answer: 0,
      explain: "Eminescu e considerat ultimul mare romantic european.",
    },
    {
      lesson: "curente-literare",
      type: "choice",
      prompt: "Care revistă a fost centrul tradiționalismului interbelic?",
      options: ["Gândirea", "Sburătorul", "Dacia literară", "Contemporanul"],
      answer: 0,
      explain: "Gândirea. Sburătorul era revista moderniștilor.",
    },
    {
      lesson: "curente-literare",
      type: "truefalse",
      prompt: "Nichita Stănescu este un poet neomodernist.",
      answer: true,
      explain: "Da, face parte din generația '60.",
    },
    {
      lesson: "curente-literare",
      type: "choice",
      prompt: "Ce trăsătură ține de simbolism?",
      options: [
        "sugestia prin simboluri și muzicalitate",
        "narator obiectiv și personaje tipice",
        "întoarcerea la valorile satului",
        "personaje excepționale în situații excepționale",
      ],
      answer: 0,
      explain: "Simbolismul sugerează. Celelalte țin de realism, tradiționalism și romantism.",
    },
    {
      lesson: "curente-literare",
      type: "truefalse",
      prompt: "Nuvela „Alexandru Lăpușneanul” a apărut în primul număr al revistei Dacia literară.",
      answer: true,
      explain: "Da, în 1840, ca nuvelă istorică romantică.",
    },
    // opere
    {
      lesson: "opere-canonice",
      type: "choice",
      prompt: "Cine a scris „Enigma Otiliei”?",
      options: ["George Călinescu", "Camil Petrescu", "Liviu Rebreanu", "Ioan Slavici"],
      answer: 0,
      explain: "George Călinescu, în 1938.",
    },
    {
      lesson: "opere-canonice",
      type: "choice",
      prompt: "Ce specie literară este „Moara cu noroc”?",
      options: ["nuvelă psihologică", "roman", "basm cult", "comedie"],
      answer: 0,
      explain: "Nuvelă psihologică realistă, publicată de Slavici în 1881.",
    },
    {
      lesson: "opere-canonice",
      type: "choice",
      prompt: "Cum își numește Marin Sorescu piesa „Iona”?",
      options: ["tragedie în patru tablouri", "comedie în patru acte", "dramă istorică", "poem dramatic"],
      answer: 0,
      explain: "„Iona” are subtitlul „tragedie în patru tablouri”.",
    },
    {
      lesson: "opere-canonice",
      type: "truefalse",
      prompt: "În „Ion”, naratorul este un personaj care povestește la persoana I.",
      answer: false,
      explain: "„Ion” are un narator omniscient, la persoana a III-a: e un roman obiectiv.",
    },
    {
      lesson: "opere-canonice",
      type: "choice",
      prompt: "Care dintre personaje apare în „O scrisoare pierdută”?",
      options: ["Nae Cațavencu", "Lică Sămădăul", "Stănică Rațiu", "Vitoria Lipan"],
      answer: 0,
      explain: "Cațavencu e cel care găsește scrisoarea și încearcă șantajul.",
    },
    {
      lesson: "opere-canonice",
      type: "choice",
      prompt: "Cine a scris romanul „Moromeții”?",
      options: ["Marin Preda", "Mihail Sadoveanu", "Liviu Rebreanu", "George Călinescu"],
      answer: 0,
      explain: "Marin Preda. Primul volum a apărut în 1955.",
    },
  ],
};
