import type { Unit } from "./types";

// Română · capitolul 2 — poeziile de studiat: „Luceafărul”, poeții moderniști,
// tradiționalismul și neomodernismul. Citatele sunt doar din Eminescu (domeniu public).

export const poezie: Unit = {
  id: "poezie",
  subject: "romana",
  title: "Poezia la bac",
  blurb: "„Luceafărul”, artele poetice moderniste, Pillat și Nichita Stănescu.",
  examRef: "Subiectul III",
  lessons: [
    {
      id: "luceafarul",
      title: "„Luceafărul”",
      cards: [
        {
          type: "learn",
          title: "Poemul pe scurt",
          body: "„Luceafărul” de **Mihai Eminescu** a apărut în **1883**, la Viena, în almanahul societății studențești „România Jună”. Are 98 de strofe.\n\nE un poem **romantic**, alegoric și filozofic. Pornește de la un basm, „Fata în grădina de aur”, cules de Richard Kunisch.\n\n**Tema**: condiția omului de geniu, care nu poate fi fericit în lumea oamenilor obișnuiți.",
        },
        {
          type: "choice",
          prompt: "În ce an a apărut „Luceafărul”?",
          options: ["1883", "1866", "1901", "1840"],
          answer: 0,
          explain: "1883, la Viena, în Almanahul Societății Academice Social-Literare „România Jună”.",
        },
        {
          type: "learn",
          title: "Patru tablouri",
          body: "**I.** Povestea de iubire dintre Cătălina, o fată de împărat, și Luceafăr. El se întrupează de două ori, o dată ca înger, o dată ca demon. Îi cere să devină nemuritoare, ea îi cere lui să devină muritor.\n\n**II.** Idila dintre Cătălina și pajul Cătălin: iubirea simplă, pământească.\n\n**III.** Zborul cosmic al Luceafărului spre Demiurg, căruia îi cere să-l facă muritor. Demiurgul refuză și îi spune pe nume: **Hyperion**.\n\n**IV.** Hyperion își vede iubita alături de Cătălin și se retrage în nemurirea lui.",
        },
        {
          type: "choice",
          prompt: "Ce nume îi dă Demiurgul Luceafărului?",
          options: ["Hyperion", "Cătălin", "Crypto", "Lucifer"],
          answer: 0,
          explain: "În tabloul al III-lea, Demiurgul i se adresează cu „Hyperion”.",
        },
        {
          type: "truefalse",
          prompt: "Pajul Cătălin reprezintă iubirea simplă, pământească, pe măsura Cătălinei.",
          answer: true,
          explain: "Cătălin e omul obișnuit. Iubirea lui e posibilă tocmai pentru că e pe măsura fetei.",
        },
        {
          type: "learn",
          title: "Finalul",
          body: "Ultima strofă e replica lui Hyperion, care închide poemul:\n\n„Trăind în cercul vostru strâmt / Norocul vă petrece, / Ci eu în lumea mea mă simt / Nemuritor și rece.”\n\nOpoziția dintre „cercul strâmt” al omului comun și nemurirea rece a geniului e ideea pe care o folosești în eseu.",
        },
        {
          type: "choice",
          prompt: "Care este tema poemului „Luceafărul”?",
          options: [
            "condiția omului de geniu",
            "viața satului tradițional",
            "războiul și moartea",
            "copilăria",
          ],
          answer: 0,
          explain: "Poemul e o alegorie despre geniu: Hyperion nu poate coborî în lumea strâmtă a omului obișnuit.",
        },
        {
          type: "calc",
          prompt: "În câte tablouri (părți) este structurat poemul?",
          answer: 4,
          explain: "Patru: iubirea Cătălinei pentru Luceafăr, idila cu Cătălin, zborul la Demiurg și finalul.",
        },
        {
          type: "truefalse",
          prompt: "Poemul pornește de la basmul „Fata în grădina de aur”.",
          answer: true,
          explain: "Eminescu a prelucrat basmul cules de Richard Kunisch.",
        },
      ],
    },
    {
      id: "poezia-moderna",
      title: "Poezia modernă",
      cards: [
        {
          type: "learn",
          title: "„Plumb”, George Bacovia",
          body: "Poezia deschide volumul **„Plumb”** (1916) și e emblema **simbolismului** românesc.\n\nPlumbul e simbolul central: greutate, apăsare, moarte, lipsa oricărei ieșiri. Totul e cenușiu, închis, rece. Repetițiile dau poeziei un ritm monoton, de litanie.\n\nTema: singurătatea și angoasa ființei închise într-o lume fără sens.",
        },
        {
          type: "choice",
          prompt: "Ce sugerează simbolul plumbului în poezia lui Bacovia?",
          options: [
            "apăsarea, moartea, lipsa de ieșire",
            "bogăția și succesul",
            "bucuria iubirii",
            "natura în primăvară",
          ],
          answer: 0,
          explain: "Plumbul e greu, cenușiu și rece: tot ce apasă ființa și o închide.",
        },
        {
          type: "learn",
          title: "„Eu nu strivesc corola de minuni a lumii”, Lucian Blaga",
          body: "Deschide volumul **„Poemele luminii”** (1919). Este o **artă poetică** modernistă: poetul spune cum vede el rostul poeziei.\n\nIdeea: poetul nu vrea să „strivească” misterul lumii prin explicații reci, ci să-l adâncească. Blaga numește asta **cunoaștere luciferică**, opusă cunoașterii raționale, **paradisiace**.\n\nOpoziția-cheie din text: „lumina mea” (a poetului) față de „lumina altora”.",
        },
        {
          type: "choice",
          prompt: "Ce fel de cunoaștere alege poetul în „Eu nu strivesc corola de minuni a lumii”?",
          options: [
            "cunoașterea luciferică, ce adâncește misterul",
            "cunoașterea rațională, care explică totul",
            "cunoașterea științifică, prin experimente",
            "renunțarea la orice cunoaștere",
          ],
          answer: 0,
          explain: "Blaga vrea să sporească misterul lumii, nu să-l desfacă prin explicații.",
        },
        {
          type: "learn",
          title: "„Testament”, Tudor Arghezi",
          body: "Deschide volumul **„Cuvinte potrivite”** (1927). Tot **artă poetică** modernistă.\n\nPoetul lasă urmașilor o „carte” în loc de avere: moștenirea lui e opera. Poezia se naște din munca și suferința strămoșilor, transformate în frumos.\n\nArghezi aduce **estetica urâtului**: din cuvinte „urâte”, de jos, poezia poate face valori noi.",
        },
        {
          type: "truefalse",
          prompt: "În „Testament”, moștenirea lăsată urmașului este o carte, adică opera poetului.",
          answer: true,
          explain: "„Cartea” e simbolul central: opera e singura avere a poetului.",
        },
        {
          type: "learn",
          title: "„Riga Crypto și lapona Enigel”, Ion Barbu",
          body: "Poem inclus în volumul **„Joc secund”** (1930), o baladă cultă, modernistă.\n\nRiga Crypto, un rege-ciupercă din lumea umedă și întunecată, o iubește pe lapona Enigel, o ființă a luminii și a rațiunii. Ea îl refuză: vrea soarele, nu umbra.\n\nTema: **incompatibilitatea** dintre două lumi care nu se pot uni, o idee pe care o recunoști și din „Luceafărul”.",
        },
        {
          type: "choice",
          prompt: "Care dintre aceste opere nu este o artă poetică?",
          options: [
            "„Riga Crypto și lapona Enigel”",
            "„Testament”",
            "„Eu nu strivesc corola de minuni a lumii”",
          ],
          answer: 0,
          explain: "„Riga Crypto” e o baladă cultă despre două lumi incompatibile. Celelalte două sunt arte poetice.",
        },
        {
          type: "choice",
          prompt: "Cu ce volum a debutat Lucian Blaga?",
          options: ["„Poemele luminii”", "„Cuvinte potrivite”", "„Plumb”", "„Joc secund”"],
          answer: 0,
          explain: "„Poemele luminii” (1919), deschis chiar cu „Eu nu strivesc corola de minuni a lumii”.",
        },
      ],
    },
    {
      id: "traditionalism-neomodernism",
      title: "Pillat și Stănescu",
      cards: [
        {
          type: "learn",
          title: "„Aci sosi pe vremuri”, Ion Pillat",
          body: "Poezie **tradiționalistă**, din volumul **„Pe Argeș în sus”** (1923).\n\nNepotul se întoarce în casa bunicilor și își imaginează cum a început, cu mulți ani în urmă, povestea de iubire a bunicului cu bunica. Apoi se vede pe sine, repetând aceeași poveste.\n\nTema: **trecerea timpului** și iubirea care se repetă de la o generație la alta.",
        },
        {
          type: "choice",
          prompt: "Cărui curent literar îi aparține poezia „Aci sosi pe vremuri”?",
          options: ["tradiționalismului", "simbolismului", "neomodernismului", "realismului"],
          answer: 0,
          explain: "Casa bătrânească, trecutul, familia și satul sunt teme tradiționaliste.",
        },
        {
          type: "truefalse",
          prompt: "În „Aci sosi pe vremuri”, povestea bunicilor se reflectă în povestea nepotului.",
          answer: true,
          explain: "Două planuri, trecut și prezent, care se oglindesc unul în altul.",
        },
        {
          type: "learn",
          title: "„Leoaică tânără, iubirea”, Nichita Stănescu",
          body: "Poezie **neomodernistă**, din volumul **„O viziune a sentimentelor”** (1964).\n\nIubirea apare brusc, ca o leoaică tânără care sare asupra poetului. Metafora arată iubirea ca pe o forță vie, surprinzătoare, care schimbă felul în care vezi lumea și pe tine însuți.\n\nTema: **iubirea ca revelație**.",
        },
        {
          type: "choice",
          prompt: "Ce reprezintă leoaica din poezia lui Nichita Stănescu?",
          options: ["iubirea", "moartea", "natura sălbatică", "războiul"],
          answer: 0,
          explain: "Titlul o spune direct: leoaica tânără este iubirea.",
        },
        {
          type: "choice",
          prompt: "Din ce volum face parte „Leoaică tânără, iubirea”?",
          options: ["„O viziune a sentimentelor”", "„Pe Argeș în sus”", "„Poemele luminii”", "„Cuvinte potrivite”"],
          answer: 0,
          explain: "„O viziune a sentimentelor” (1964).",
        },
        {
          type: "learn",
          title: "Cum le folosești în eseu",
          body: "La eseul despre un text poetic ți se cere de obicei: **tema** și viziunea despre lume, două **imagini sau idei poetice** care o ilustrează, și două **elemente de compoziție și limbaj** (titlu, incipit, final, simboluri, figuri de stil, relații de opoziție).\n\nSfatul: pentru fiecare poezie, ține minte titlul volumului, anul, curentul și **o opoziție centrală**. De exemplu: „lumina mea” și „lumina altora” la Blaga, sau trecut și prezent la Pillat.",
        },
        {
          type: "truefalse",
          prompt: "Nichita Stănescu și Ion Pillat aparțin aceluiași curent literar.",
          answer: false,
          explain: "Pillat e tradiționalist (interbelic), Stănescu e neomodernist (după anii '60).",
        },
      ],
    },
  ],
  test: [
    // Luceafărul
    {
      lesson: "luceafarul",
      type: "choice",
      prompt: "Cine este Cătălina în „Luceafărul”?",
      options: ["o fată de împărat", "o laponă", "o țărancă din sat", "o zeiță"],
      answer: 0,
      explain: "Chiar prima strofă o spune: „Din rude mari împărătești, / O prea frumoasă fată”.",
    },
    {
      lesson: "luceafarul",
      type: "truefalse",
      prompt: "În „Luceafărul”, Demiurgul acceptă să-l facă pe Hyperion muritor.",
      answer: false,
      explain: "Demiurgul refuză: nemurirea e esența lui Hyperion.",
    },
    {
      lesson: "luceafarul",
      type: "choice",
      prompt: "Cărui curent îi aparține „Luceafărul”?",
      options: ["romantismului", "simbolismului", "modernismului", "realismului"],
      answer: 0,
      explain: "E un poem romantic: geniul, visul, cosmosul, iubirea imposibilă.",
    },
    {
      lesson: "luceafarul",
      type: "choice",
      prompt: "Unde a apărut prima dată „Luceafărul”?",
      options: ["la Viena, în almanahul „România Jună”", "în revista Sburătorul", "în revista Gândirea", "în Dacia literară"],
      answer: 0,
      explain: "În 1883, în almanahul societății „România Jună” din Viena.",
    },
    // poezia modernă
    {
      lesson: "poezia-moderna",
      type: "choice",
      prompt: "Cine a scris „Testament”?",
      options: ["Tudor Arghezi", "Lucian Blaga", "Ion Barbu", "George Bacovia"],
      answer: 0,
      explain: "Tudor Arghezi, în volumul „Cuvinte potrivite” (1927).",
    },
    {
      lesson: "poezia-moderna",
      type: "choice",
      prompt: "Ce înseamnă „estetica urâtului” la Arghezi?",
      options: [
        "din cuvinte și realități urâte se poate crea frumos",
        "poezia trebuie să evite orice e urât",
        "doar natura poate fi frumoasă",
        "poezia trebuie să fie scrisă fără rimă",
      ],
      answer: 0,
      explain: "Arghezi transformă urâtul în material poetic și îi dă valoare estetică.",
    },
    {
      lesson: "poezia-moderna",
      type: "truefalse",
      prompt: "Volumul „Plumb” al lui George Bacovia a apărut în 1916.",
      answer: true,
      explain: "Da, 1916.",
    },
    {
      lesson: "poezia-moderna",
      type: "choice",
      prompt: "De ce o refuză lapona Enigel pe Riga Crypto?",
      options: [
        "ea aparține luminii, el umbrei: lumile lor nu se pot uni",
        "el este prea sărac",
        "ea iubește pe altcineva din sat",
        "părinții ei nu sunt de acord",
      ],
      answer: 0,
      explain: "Tema poemului e incompatibilitatea dintre două lumi.",
    },
    {
      lesson: "poezia-moderna",
      type: "choice",
      prompt: "Ce tip de text este „Eu nu strivesc corola de minuni a lumii”?",
      options: ["artă poetică", "baladă cultă", "pastel", "poem epic"],
      answer: 0,
      explain: "O artă poetică: Blaga își explică felul de a înțelege poezia și cunoașterea.",
    },
    // Pillat și Stănescu
    {
      lesson: "traditionalism-neomodernism",
      type: "choice",
      prompt: "Cine a scris „Aci sosi pe vremuri”?",
      options: ["Ion Pillat", "Vasile Voiculescu", "Mihai Eminescu", "Lucian Blaga"],
      answer: 0,
      explain: "Ion Pillat, în volumul „Pe Argeș în sus” (1923).",
    },
    {
      lesson: "traditionalism-neomodernism",
      type: "choice",
      prompt: "Care este tema poeziei „Aci sosi pe vremuri”?",
      options: [
        "trecerea timpului și iubirea repetată în generații",
        "condiția omului de geniu",
        "războiul",
        "cunoașterea luciferică",
      ],
      answer: 0,
      explain: "Povestea bunicilor se repetă în povestea nepotului.",
    },
    {
      lesson: "traditionalism-neomodernism",
      type: "truefalse",
      prompt: "„Leoaică tânără, iubirea” prezintă iubirea ca pe o revelație bruscă.",
      answer: true,
      explain: "Iubirea „sare” asupra poetului și îi schimbă felul de a vedea lumea.",
    },
    {
      lesson: "traditionalism-neomodernism",
      type: "choice",
      prompt: "În ce an a apărut volumul „O viziune a sentimentelor”?",
      options: ["1964", "1923", "1919", "1883"],
      answer: 0,
      explain: "1964, în plin neomodernism.",
    },
  ],
};
